import React, { useEffect, useState } from 'react';
import { ArrowRight, Bell, Check, Clock3, Heart, Leaf, LogOut, MapPin, PackagePlus, ShieldCheck, Sparkles, Trash2, Utensils, X } from 'lucide-react';
import { createRoot } from 'react-dom/client';
import { CircleMarker, MapContainer, TileLayer, Popup } from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
import './styles.css';

const api = `${import.meta.env.VITE_API_URL || 'http://localhost:5000'}/api`;
const statusClass = value => `status ${value.toLowerCase().replace('_', '-')}`;
const emptyForm = { foodName: '', foodType: 'Cooked meal', quantity: '', unit: 'meals', expiryTime: '', pickupLocation: '', description: '' };
const formatExpiry = value => { const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' }); };

function MapView({ coordinates, address }) {
  if (!coordinates?.latitude || !coordinates?.longitude) return null;
  return <div className="map-wrap"><MapContainer center={[coordinates.latitude, coordinates.longitude]} zoom={13} scrollWheelZoom={false}><TileLayer attribution="&copy; OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" /><CircleMarker center={[coordinates.latitude, coordinates.longitude]} radius={9} pathOptions={{ color: '#397c53', fillColor: '#d9ef91', fillOpacity: 0.9 }}><Popup>{address}</Popup></CircleMarker></MapContainer></div>;
}

function App() {
  const [donations, setDonations] = useState([]);
  const [donationSearch, setDonationSearch] = useState('');
  const [donationType, setDonationType] = useState('all');
  const [user, setUser] = useState(null);
  const [stats, setStats] = useState(null);
  const [modal, setModal] = useState(null);
  const [authMode, setAuthMode] = useState('login');
  const [authForm, setAuthForm] = useState({ name: '', email: '', password: '', role: 'donor' });
  const [form, setForm] = useState(emptyForm);
  const [profileForm, setProfileForm] = useState({ name: '', phone: '', profileImage: '' });
  const [passwordForm, setPasswordForm] = useState({ currentPassword: '', newPassword: '' });
  const [adminNGOs, setAdminNGOs] = useState([]);
  const [adminStats, setAdminStats] = useState(null);
  const [pickupForm, setPickupForm] = useState({ donationId: '', scheduledDate: '', scheduledTime: '', notes: '' });
  const [notifications, setNotifications] = useState([]);
  const [unreadCount, setUnreadCount] = useState(0);
  const [notice, setNotice] = useState('');
  const [uploadProgress, setUploadProgress] = useState(0);

  const request = async (path, options = {}) => {
    const token = localStorage.getItem('token');
    const response = await fetch(`${api}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(options.headers || {}) } });
    const data = await response.json();
    if (!response.ok) throw new Error(data.message || 'Something went wrong.');
    return data;
  };
  const uploadRequest = (path, formData, method = 'POST') => new Promise((resolve, reject) => { const xhr = new XMLHttpRequest(); xhr.open(method, `${api}${path}`); const token = localStorage.getItem('token'); if (token) xhr.setRequestHeader('Authorization', `Bearer ${token}`); xhr.upload.onprogress = event => { if (event.lengthComputable) setUploadProgress(Math.round(event.loaded / event.total * 100)); }; xhr.onload = () => { try { const data = JSON.parse(xhr.responseText); if (xhr.status >= 200 && xhr.status < 300) resolve(data); else reject(new Error(data.message || 'Upload failed.')); } catch { reject(new Error('Upload failed.')); } }; xhr.onerror = () => reject(new Error('Upload failed.')); xhr.onloadend = () => setUploadProgress(0); xhr.send(formData); });
  const loadDonations = () => request('/donations').then(setDonations).catch(() => setNotice('Start the API server to see live donations.'));
  const loadWorkspace = () => request('/dashboard').then(setStats).catch(() => setStats(null));
  const loadNotifications = async () => { if (!localStorage.getItem('token')) return; try { const [items, unread] = await Promise.all([request('/notifications'), request('/notifications/unread-count')]); setNotifications(items); setUnreadCount(unread.count); } catch { setNotifications([]); } };

  useEffect(() => {
    loadDonations();
    const token = localStorage.getItem('token');
    if (token) request('/auth/me').then(account => { setUser(account); loadWorkspace(); }).catch(() => localStorage.removeItem('token'));
  }, []);
  useEffect(() => { if (!user) return undefined; loadNotifications(); const timer = setInterval(loadNotifications, 45000); return () => clearInterval(timer); }, [user]);

  const authenticate = async event => {
    event.preventDefault();
    try {
      const path = authMode === 'login' ? '/auth/login' : '/auth/register';
      const data = await request(path, { method: 'POST', body: JSON.stringify(authForm) });
      localStorage.setItem('token', data.token); setUser(data.user); setProfileForm({ name: data.user.name, phone: data.user.phone || '', profileImage: data.user.profileImage || '' }); setModal(null); setNotice(`Welcome, ${data.user.name}.`); loadWorkspace();
    } catch (error) { setNotice(error.message); }
  };
  const signOut = () => { request('/auth/logout', { method: 'POST' }).catch(() => {}); localStorage.removeItem('token'); setUser(null); setStats(null); setNotice('You have been signed out.'); };
  const openProfile = () => { setProfileForm({ name: user.name, phone: user.phone || '', profileImage: user.profileImage || '' }); setModal('profile'); };
  const updateProfile = async event => { event.preventDefault(); try { const { profileImageFile, ...profile } = profileForm; const updated = await request('/users/me', { method: 'PUT', body: JSON.stringify(profile) }); const finalUser = profileImageFile ? await uploadRequest('/users/profile-image', (() => { const data = new FormData(); data.append('image', profileImageFile); return data; })(), 'PUT') : updated; setUser(finalUser); setModal(null); setNotice('Profile updated successfully.'); } catch (error) { setNotice(error.message); } };
  const changePassword = async event => { event.preventDefault(); try { await request('/users/change-password', { method: 'PUT', body: JSON.stringify(passwordForm) }); setPasswordForm({ currentPassword: '', newPassword: '' }); setModal(null); setNotice('Password updated successfully.'); } catch (error) { setNotice(error.message); } };
  const openAdmin = async () => { try { const [ngos, summary] = await Promise.all([request('/admin/ngos'), request('/admin/dashboard/stats')]); setAdminNGOs(ngos); setAdminStats(summary); setModal('admin'); } catch (error) { setNotice(error.message); } };
  const markNotificationRead = async notification => { try { if (!notification.isRead) await request(`/notifications/${notification.id}/read`, { method: 'PUT' }); setNotifications(items => items.map(item => item.id === notification.id ? { ...item, isRead: true } : item)); setUnreadCount(count => Math.max(count - (notification.isRead ? 0 : 1), 0)); if (notification.relatedDonationId) document.getElementById('donations')?.scrollIntoView({ behavior: 'smooth' }); } catch (error) { setNotice(error.message); } };
  const markAllNotificationsRead = async () => { try { await request('/notifications/read-all', { method: 'PUT' }); setNotifications(items => items.map(item => ({ ...item, isRead: true }))); setUnreadCount(0); } catch (error) { setNotice(error.message); } };
  const deleteNotification = async id => { try { await request(`/notifications/${id}`, { method: 'DELETE' }); setNotifications(items => items.filter(item => item.id !== id)); } catch (error) { setNotice(error.message); } };
  const useCurrentLocation = () => { if (!navigator.geolocation) return setNotice('Location is not supported by this browser.'); navigator.geolocation.getCurrentPosition(position => setForm(value => ({ ...value, latitude: position.coords.latitude, longitude: position.coords.longitude })), error => setNotice(error.code === error.PERMISSION_DENIED ? 'Location permission was denied. You can enter the pickup area manually.' : 'Unable to read your location.')); };
  const verifyNGO = async (id, action) => { try { const updated = await request(`/admin/ngos/${id}/${action}`, { method: 'PUT', body: JSON.stringify(action === 'reject' ? { reason: 'Please provide the missing verification information.' } : {}) }); setAdminNGOs(items => items.map(item => item.id === updated.id ? updated : item)); setNotice(`NGO ${action === 'verify' ? 'verified' : 'rejected'}.`); } catch (error) { setNotice(error.message); } };
  const submitDonation = async event => {
    event.preventDefault();
    try { let donation; if (form.imageFile) { const data = new FormData(); Object.entries(form).filter(([key]) => !['imageFile', 'imagePreview'].includes(key) && form[key] !== '').forEach(([key, value]) => data.append(key, value)); data.append('image', form.imageFile); donation = await uploadRequest('/donations', data); } else donation = await request('/donations', { method: 'POST', body: JSON.stringify(form) }); setDonations(items => [donation, ...items]); setForm(emptyForm); setModal(null); setNotice('Donation published. Nearby partners can now request it.'); loadWorkspace(); }
    catch (error) { setNotice(error.message); }
  };
  const updateStatus = async (id, status) => {
    try { const updated = await request(status === 'ACCEPTED' ? `/donations/${id}/accept` : `/donations/${id}/status`, { method: status === 'ACCEPTED' ? 'POST' : 'PATCH', body: status === 'ACCEPTED' ? undefined : JSON.stringify({ status }) }); setDonations(items => items.map(item => item.id === id ? updated : item)); setNotice(`Donation marked ${status.toLowerCase().replace('_', ' ')}.`); loadWorkspace(); }
    catch (error) { setNotice(error.message); }
  };
  const schedulePickup = async event => { event.preventDefault(); try { await request('/pickups', { method: 'POST', body: JSON.stringify(pickupForm) }); setPickupForm({ donationId: '', scheduledDate: '', scheduledTime: '', notes: '' }); setModal(null); setNotice('Pickup scheduled successfully.'); loadDonations(); } catch (error) { setNotice(error.message); } };

  const normalizedSearch = donationSearch.trim().toLowerCase();
  const visibleDonations = donations.filter(donation => {
    const matchesType = donationType === 'all' || donation.foodType === donationType;
    const searchableText = [donation.foodName, donation.pickupLocation, donation.description].filter(Boolean).join(' ').toLowerCase();
    return matchesType && (!normalizedSearch || searchableText.includes(normalizedSearch));
  });

  return <>
    <a className="skip" href="#main">Skip to content</a>
    <header><a className="brand" href="#top"><span className="brand-mark"><Leaf size={22} /></span>FeedingMe</a><nav aria-label="Main navigation"><a href="#how">How it works</a><a href="#impact">Our impact</a><a href="#donations">Nearby food</a></nav>{user ? <div className="account"><button className="icon-button notification-button" title="Notifications" onClick={() => setModal('notifications')}><Bell size={17} />{unreadCount > 0 && <b>{unreadCount > 99 ? '99+' : unreadCount}</b>}</button><button className="account-name" onClick={openProfile}>{user.name}</button>{user.role === 'admin' && <button className="icon-button" title="Manage NGOs" onClick={openAdmin}><ShieldCheck size={17} /></button>}<button className="icon-button" title="Sign out" onClick={signOut}><LogOut size={17} /></button></div> : <button className="link-button" onClick={() => { setAuthMode('login'); setModal('auth'); }}>Sign in</button>}<button className="button small" onClick={() => user ? setModal('donate') : setModal('auth')}>{user ? 'Donate food' : 'Join FeedingMe'} <ArrowRight size={17} /></button></header>
    <main id="main">
      <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow"><Heart size={16} /> A better route for good food</p><h1>Good food deserves<br /><em>a second table.</em></h1><p className="lede">Connect surplus food with local people and organisations who can turn it into a meal - today.</p><div className="hero-actions"><button className="button" onClick={() => user ? setModal('donate') : setModal('auth')}>Share food <ArrowRight size={18} /></button><a className="text-action" href="#how">See how it works <ArrowRight size={16} /></a></div><div className="trust"><span><ShieldCheck size={18} /> Verified local partners</span><span><Clock3 size={18} /> Time-sensitive matching</span></div></div><div className="hero-art" role="img" aria-label="Fresh vegetables arranged in a basket"><div className="orb orb-one" /><div className="orb orb-two" /><div className="basket"><div className="basket-handle" /><div className="produce tomato" /><div className="produce lemon" /><div className="produce leaf-a" /><div className="produce leaf-b" /><div className="basket-base" /></div><div className="impact-note"><span>Meals made possible</span><strong>12,480</strong><small>this month <ArrowRight size={13} /></small></div></div></section>
      <section className="impact-strip" id="impact"><div><strong>48k</strong><span>meals shared</span></div><div><strong>126</strong><span>local partners</span></div><div><strong>18.4t</strong><span>food rescued</span></div><p>Small actions, kept close to home.<br /><b>That's how change travels.</b></p></section>
      <section className="how" id="how"><p className="eyebrow green"><Utensils size={16} /> Simple by design</p><h2>From extra to essential,<br />in three thoughtful steps.</h2><div className="steps"><article><span>01</span><h3>Post what you have</h3><p>Tell us what's available, how much, and when it needs to be collected.</p></article><article><span>02</span><h3>Match locally</h3><p>Nearby verified partners see the offer and request a pickup.</p></article><article><span>03</span><h3>Make it count</h3><p>Track the handover and see the meals your contribution made possible.</p></article></div></section>
      {user && stats && <section className="workspace"><div className="section-head"><div><p className="eyebrow green"><Sparkles size={16} /> Your workspace</p><h2>{user.role === 'ngo' ? 'Find food to collect.' : 'Your impact, in motion.'}</h2></div><button className="button small" onClick={() => setModal('donate')}><PackagePlus size={16} /> New donation</button></div><div className="stat-grid"><div><strong>{stats.total}</strong><span>{user.role === 'ngo' ? 'visible donations' : 'your donations'}</span></div><div><strong>{stats.available}</strong><span>available now</span></div><div><strong>{stats.completed}</strong><span>completed</span></div><div><strong>{stats.meals}</strong><span>meals shared</span></div></div></section>}
      <section className="nearby" id="donations"><div className="section-head"><div><p className="eyebrow green"><MapPin size={16} /> Around you</p><h2>Food ready for a good home.</h2></div><button className="outline" onClick={loadDonations}>Refresh list</button></div><div className="donation-controls"><label>Search food or area<input type="search" value={donationSearch} onChange={event => setDonationSearch(event.target.value)} placeholder="Food name or pickup area" /></label><label>Food type<select value={donationType} onChange={event => setDonationType(event.target.value)}><option value="all">All food types</option><option>Cooked meal</option><option>Bakery</option><option>Fresh produce</option><option>Packaged food</option></select></label><p className="results-count" aria-live="polite">{visibleDonations.length} {visibleDonations.length === 1 ? 'donation' : 'donations'} shown</p></div><div className="donation-grid">{visibleDonations.length ? visibleDonations.map(d => <article className="donation-card" key={d.id}>{(d.image?.url || d.imageUrl) && <img className="food-photo" src={d.image?.url || d.imageUrl} alt={d.foodName} loading="lazy" onError={event => { event.currentTarget.style.display = 'none'; }} />}<div className="card-top"><div className="food-icon"><Utensils size={22} /></div><span className={statusClass(d.status)}>{d.status.replace('_', ' ')}</span></div><h3>{d.foodName}</h3><p>{d.quantity} {d.unit} · {d.foodType}</p><div className="details"><span><Clock3 size={16} /> {formatExpiry(d.expiryTime)}</span><span><MapPin size={16} /> {d.pickupLocation}</span></div><MapView coordinates={d.pickupCoordinates} address={d.pickupLocation} />{user?.role === 'ngo' && d.status === 'AVAILABLE' ? <button className="card-action" onClick={() => updateStatus(d.id, 'ACCEPTED')}>Accept pickup <Check size={17} /></button> : user?.role === 'ngo' && d.status === 'ACCEPTED' ? <button className="card-action" onClick={() => { setPickupForm({ ...pickupForm, donationId: d.id }); setModal('pickup'); }}>Schedule pickup <Clock3 size={17} /></button> : user?.role === 'donor' && d.donorId === user.id ? <button className="card-action muted-action" onClick={() => setNotice(`This donation is ${d.status.toLowerCase().replace('_', ' ')}.`)}>View status <ArrowRight size={17} /></button> : <button className="card-action" onClick={() => setModal('auth')}>I can collect <ArrowRight size={17} /></button>}</article>) : <p className="empty">{donations.length ? "No donations match those filters. Try another search or food type." : "No donations yet. Be the first to share food."}</p>}</div></section>
      <section className="cta"><div><p className="eyebrow"><Heart size={16} /> Your surplus can be someone's supper</p><h2>Make room for<br /><em>more good.</em></h2></div><button className="button light" onClick={() => user ? setModal('donate') : setModal('auth')}>Donate food <ArrowRight size={18} /></button></section>
    </main><footer><a className="brand" href="#top"><span className="brand-mark"><Leaf size={22} /></span>FeedingMe</a><span>Built for neighbours helping neighbours.</span></footer>
    {notice && <div className="notice" role="status">{notice}<button aria-label="Dismiss message" onClick={() => setNotice('')}><X size={17} /></button></div>}
    {modal === 'profile' && <div className="overlay"><section className="modal" role="dialog" aria-modal="true"><button className="close" aria-label="Close profile" onClick={() => setModal(null)}><X /></button><p className="eyebrow green"><ShieldCheck size={16} /> Account profile</p><h2>Keep your details current.</h2><p className="modal-copy">Role: {user?.role}. Your role can only be changed by an administrator.</p><form onSubmit={updateProfile}><label>Name<input required minLength="2" value={profileForm.name} onChange={e => setProfileForm({ ...profileForm, name: e.target.value })} /></label><label>Phone<input value={profileForm.phone} onChange={e => setProfileForm({ ...profileForm, phone: e.target.value })} placeholder="+91 98765 43210" /></label><label>Profile image<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e => { const file = e.target.files?.[0]; if (file) setProfileForm({ ...profileForm, profileImageFile: file }); }} /></label>{profileForm.profileImageFile && <small className="location-note">Selected: {profileForm.profileImageFile.name}</small>}<button className="button full" type="submit">Save profile {uploadProgress > 0 && `(${uploadProgress}%)`} <Check size={18} /></button></form><button className="switch-auth" onClick={() => setModal('password')}>Change password</button></section></div>}
    {modal === 'password' && <div className="overlay"><section className="modal" role="dialog" aria-modal="true"><button className="close" aria-label="Close password form" onClick={() => setModal(null)}><X /></button><p className="eyebrow green"><ShieldCheck size={16} /> Password security</p><h2>Change your password.</h2><form onSubmit={changePassword}><label>Current password<input required type="password" value={passwordForm.currentPassword} onChange={e => setPasswordForm({ ...passwordForm, currentPassword: e.target.value })} /></label><label>New password<input required minLength="8" type="password" value={passwordForm.newPassword} onChange={e => setPasswordForm({ ...passwordForm, newPassword: e.target.value })} placeholder="At least 8 characters" /></label><button className="button full" type="submit">Update password <Check size={18} /></button></form></section></div>}
    {modal === 'admin' && <div className="overlay"><section className="modal wide-modal" role="dialog" aria-modal="true"><button className="close" aria-label="Close NGO management" onClick={() => setModal(null)}><X /></button><p className="eyebrow green"><ShieldCheck size={16} /> Command center</p><h2>Platform, in one view.</h2>{adminStats && <div className="admin-stat-grid"><div><strong>{adminStats.users.total}</strong><span>users</span></div><div><strong>{adminStats.ngos.verified}</strong><span>verified NGOs</span></div><div><strong>{adminStats.donations.total}</strong><span>donations</span></div><div><strong>{adminStats.pickups.active}</strong><span>active pickups</span></div><div><strong>{adminStats.impact.totalQuantity}</strong><span>food quantity</span></div><div><strong>{adminStats.impact.completedQuantity}</strong><span>completed quantity</span></div></div>}<h3 className="admin-subheading">NGO verification queue</h3><div className="admin-list">{adminNGOs.length ? adminNGOs.map(ngo => <article className="admin-row" key={ngo.id}><div><strong>{ngo.organizationName}</strong><span>{ngo.email} · {ngo.verificationStatus}</span></div><div className="admin-actions">{ngo.verificationStatus !== 'VERIFIED' && <button className="outline" onClick={() => verifyNGO(ngo.id, 'verify')}>Verify</button>}{ngo.verificationStatus !== 'REJECTED' && <button className="outline danger" onClick={() => verifyNGO(ngo.id, 'reject')}>Reject</button>}</div></article>) : <p className="empty">No NGO profiles have been submitted.</p>}</div></section></div>}
    {modal === 'notifications' && <div className="overlay"><section className="modal wide-modal notification-modal" role="dialog" aria-modal="true"><button className="close" aria-label="Close notifications" onClick={() => setModal(null)}><X /></button><div className="notification-heading"><div><p className="eyebrow green"><Bell size={16} /> Notification center</p><h2>Updates that matter.</h2></div><button className="outline" onClick={markAllNotificationsRead}>Mark all read</button></div><div className="notification-list">{notifications.length ? notifications.map(item => <article className={`notification-item ${item.isRead ? 'read' : 'unread'}`} key={item.id} onClick={() => markNotificationRead(item)}><div><strong>{item.title}</strong><p>{item.message}</p><small>{formatExpiry(item.createdAt)}</small></div><button className="icon-button" title="Delete notification" onClick={event => { event.stopPropagation(); deleteNotification(item.id); }}><Trash2 size={16} /></button></article>) : <p className="empty">No notifications yet.</p>}</div></section></div>}
    {modal === 'pickup' && <div className="overlay"><section className="modal" role="dialog" aria-modal="true"><button className="close" aria-label="Close pickup form" onClick={() => setModal(null)}><X /></button><p className="eyebrow green"><Clock3 size={16} /> Pickup coordination</p><h2>Schedule the handover.</h2><form onSubmit={schedulePickup}><label>Date<input required type="date" value={pickupForm.scheduledDate} min={new Date().toISOString().slice(0, 10)} onChange={e => setPickupForm({ ...pickupForm, scheduledDate: e.target.value })} /></label><label>Time<input required type="time" value={pickupForm.scheduledTime} onChange={e => setPickupForm({ ...pickupForm, scheduledTime: e.target.value })} /></label><label>Notes<textarea value={pickupForm.notes} onChange={e => setPickupForm({ ...pickupForm, notes: e.target.value })} placeholder="Gate, contact, or handover notes" /></label><button className="button full" type="submit">Schedule pickup <Check size={18} /></button></form></section></div>}
    {modal === 'auth' && <div className="overlay"><section className="modal" role="dialog" aria-modal="true"><button className="close" aria-label="Close" onClick={() => setModal(null)}><X /></button><p className="eyebrow green"><Heart size={16} /> {authMode === 'login' ? 'Welcome back' : 'Start helping'}</p><h2>{authMode === 'login' ? 'Sign in to FeedingMe' : 'Create your account'}</h2><p className="modal-copy">{authMode === 'login' ? 'Pick up where your good work left off.' : 'Join donors and local organisations making food count.'}</p><form onSubmit={authenticate}>{authMode === 'register' && <label>Your name<input required value={authForm.name} onChange={e => setAuthForm({ ...authForm, name: e.target.value })} placeholder="Asha Kitchen" /></label>}<label>Email<input required type="email" value={authForm.email} onChange={e => setAuthForm({ ...authForm, email: e.target.value })} placeholder="you@example.com" /></label><label>Password<input required minLength="8" type="password" value={authForm.password} onChange={e => setAuthForm({ ...authForm, password: e.target.value })} placeholder="At least 8 characters" /></label>{authMode === 'register' && <label>I am joining as<select value={authForm.role} onChange={e => setAuthForm({ ...authForm, role: e.target.value })}><option value="donor">A food donor</option><option value="ngo">An NGO or trust</option></select></label>}<button className="button full" type="submit">{authMode === 'login' ? 'Sign in' : 'Create account'} <ArrowRight size={18} /></button></form><button className="switch-auth" onClick={() => setAuthMode(authMode === 'login' ? 'register' : 'login')}>{authMode === 'login' ? 'New here? Create an account' : 'Already have an account? Sign in'}</button></section></div>}
    {modal === 'donate' && <div className="overlay"><section className="modal" role="dialog" aria-modal="true"><button className="close" aria-label="Close donation form" onClick={() => setModal(null)}><X /></button><p className="eyebrow green"><PackagePlus size={16} /> Share food</p><h2>Post a donation</h2><p className="modal-copy">A few details help the right local partner respond quickly.</p><form onSubmit={submitDonation}><label>Food name<input required value={form.foodName} onChange={e => setForm({ ...form, foodName: e.target.value })} placeholder="e.g. Vegetable pulao" /></label><div className="form-row"><label>Quantity<input required min="1" type="number" value={form.quantity} onChange={e => setForm({ ...form, quantity: e.target.value })} placeholder="35" /></label><label>Unit<select value={form.unit} onChange={e => setForm({ ...form, unit: e.target.value })}><option>meals</option><option>kg</option><option>packs</option></select></label></div><label>Food type<select value={form.foodType} onChange={e => setForm({ ...form, foodType: e.target.value })}><option>Cooked meal</option><option>Bakery</option><option>Fresh produce</option><option>Packaged food</option></select></label><label>Collect before<input required type="datetime-local" value={form.expiryTime} onChange={e => setForm({ ...form, expiryTime: e.target.value })} /></label><label>Pickup area<input required value={form.pickupLocation} onChange={e => setForm({ ...form, pickupLocation: e.target.value })} placeholder="Anna Nagar, Chennai" /></label><label>Food image <input type="file" accept="image/jpeg,image/png,image/webp" onChange={e => { const file = e.target.files?.[0]; if (file) setForm({ ...form, imageFile: file, imagePreview: URL.createObjectURL(file) }); }} /></label>{form.imagePreview && <img className="upload-preview" src={form.imagePreview} alt="Selected food" />}<button className="location-button" type="button" onClick={useCurrentLocation}><MapPin size={16} /> Use current location</button>{form.latitude && <small className="location-note">Location captured. You can still edit the pickup area above.</small>}<button className="button full" type="submit" disabled={uploadProgress > 0}>{uploadProgress > 0 ? `Uploading ${uploadProgress}%` : 'Publish donation'} <ArrowRight size={18} /></button></form></section></div>}
  </>;
}

createRoot(document.getElementById('root')).render(<App />);
